// developer-waypoints/season-2/episode1/src/app/here-map/here-map.component.ts
import { Component, OnInit, ViewChild, ElementRef, Input } from '@angular/core';

declare var H: any;

@Component({
    selector: 'here-map',
    templateUrl: './here-map.component.html',
    styleUrls: ['./here-map.component.css']
})
export class HereMapComponent implements OnInit {

    private platform: any;
    private map: any;

    @ViewChild("map", { static: false })
    private mapElement: ElementRef;

    @Input("appid")
    private appId: string;

    @Input("appcode")
    private appCode: string;

    @Input("zoom")
    private zoom: number;

    @Input("lat")
    private lat: number;

    @Input("lng")
    private lng: number;

    public constructor() { }

    public ngOnInit() {
        this.platform = new H.service.Platform({
            "app_id": this.appId,
            "app_code": this.appCode
        });
    }

    public ngAfterViewInit() {
        this.map = new H.Map(
            this.mapElement.nativeElement,
            this.platform.createDefaultLayers().normal.map,
            {
                zoom: this.zoom,
                center: { lat: this.lat, lng: this.lng }
            }
        );
        let mapEvents = new H.mapevents.MapEvents(this.map);
        let behavior = new H.mapevents.Behavior(mapEvents);
    }

    public dropMarker(position: any) {
        let marker = new H.map.Marker(position);
        this.map.addObject(marker);
    }

    public drawLine(pos1: any, pos2: any) {
        let lineString = new H.geo.LineString();
        lineString.pushPoint(pos1);
        lineString.pushPoint(pos2);
        let polyline = new H.map.Polyline(
            lineString,
            {
                style: {
                    lineWidth: 5
                }
            }
        );
        this.map.addObject(polyline);
    }

}

// developer-waypoints/season-2/episode6/src/components/HereMap.vue
<template>
    <div>
        <div ref="map" id="map"></div>
    </div>
</template>

<script>
    export default {
        name: 'HereMap',
        props: {
            apiKey: String
        },
        data() {
            return {
                platform: {},
                map: {}
            }
        },
        created() {
            this.platform = new H.service.Platform({
                apikey: this.apiKey
            });
        },
        mounted() {
            this.map = new H.Map(
                this.$refs.map,
                this.platform.createDefaultLayers().vector.normal.map,
                {
                    center: { lat: 37, lng: -121 },
                    zoom: 10
                }
            );
            let mapEvent = new H.mapevents.MapEvents(this.map);
            let behavior = new H.mapevents.Behavior(mapEvent);
            this.dropMarker({ lat: 37, lng: -121 });
        },
        methods: {
            dropMarker(position) {
                let marker = new H.map.Marker(position);
                this.map.addObject(marker);
            },
            drawCircle(position, radius) {
                let circle = new H.map.Circle(position, radius);
                this.map.addObject(circle);
            },
            drawLine(start, finish) {
                let lineString = new H.geo.LineString();
                lineString.pushPoint(start);
                lineString.pushPoint(finish);
                let polyline = new H.map.Polyline(
                    lineString,
                    {
                        style: {
                            lineWidth: 7
                        }
                    }
                );
                this.map.addObject(polyline);
            }
        }
    }
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
    #map {
        width: 100vw; 
        height: 100vh; 
        background-color: pink;
    }
</style>
